# Generated by Django 4.2.20 on 2025-04-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brand', models.CharField(choices=[('Rolex', 'Rolex'), ('Casio', 'Casio'), ('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=50, verbose_name='Бренд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('gender', models.CharField(choices=[('men', 'Мужские'), ('women', 'Женские')], max_length=10, verbose_name='Для кого')),
                ('material', models.CharField(choices=[('plastic', 'Пластик'), ('aluminum', 'Алюминий'), ('steel', 'Нержавеющая сталь'), ('brass', 'Латунь'), ('titanium', 'Титан'), ('ceramic', 'Керамика'), ('carbon', 'Карбон'), ('gold', 'Золото'), ('platinum', 'Платина')], max_length=100, verbose_name='Материал корпуса')),
                ('strap_material', models.CharField(blank=True, max_length=100, verbose_name='Материал ремешка')),
                ('water_resistance', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=50, verbose_name='Водонепроницаемость')),
                ('movement', models.CharField(choices=[('mechanical', 'Механические (ручной завод)'), ('automatic', 'Автоматические'), ('quartz', 'Кварцевые'), ('solar', 'Солнечные'), ('smart', 'Умные часы')], max_length=50, verbose_name='Механизм')),
                ('dial_color', models.CharField(blank=True, max_length=50, verbose_name='Цвет циферблата')),
                ('case_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диаметр корпуса (мм)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
