# Generated by Django 4.2.18 on 2025-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(upload_to="carousel/")),
                ("link", models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(
                choices=[
                    ("men", "Мужские(Сардор)"),
                    ("women", "Женские(Саид)"),
                    ("unisex", "Унисекс"),
                    ("other", "Другое"),
                ],
                max_length=10,
                verbose_name="Для кого",
            ),
        ),
    ]
