# Generated by Django 4.2.18 on 2025-04-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_carouselitem_alter_watch_gender"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarouselItem",
        ),
        migrations.RenameField(
            model_name="watch",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="case_diameter",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="dial_color",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="strap_material",
        ),
        migrations.AlterField(
            model_name="watch",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Rolex", "Rolex"),
                    ("Casio", "Casio"),
                    ("Apple", "Apple"),
                    ("Samsung", "Samsung"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(
                choices=[
                    ("men", "Мужские"),
                    ("women", "Женские"),
                    ("unisex", "Унисекс"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="watches/"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="material",
            field=models.CharField(
                choices=[
                    ("plastic", "Пластик"),
                    ("aluminum", "Алюминий"),
                    ("steel", "Нержавеющая сталь"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement",
            field=models.CharField(
                choices=[
                    ("mechanical", "Механические"),
                    ("automatic", "Автоматические"),
                    ("quartz", "Кварцевые"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(
                choices=[("yes", "Да"), ("no", "Нет")], max_length=50
            ),
        ),
    ]
