# Generated by Django 4.2.18 on 2025-04-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_carouselitem_rename_name_watch_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя автора")),
                (
                    "picture",
                    models.ImageField(upload_to="authors/", verbose_name="Фото автора"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
            ],
        ),
        migrations.AlterField(
            model_name="watch",
            name="brand",
            field=models.CharField(
                choices=[
                    ("Rolex", "Rolex"),
                    ("Casio", "Casio"),
                    ("Apple", "Apple"),
                    ("Samsung", "Samsung"),
                ],
                max_length=50,
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(
                choices=[
                    ("men", "Мужские"),
                    ("women", "Женские"),
                    ("unisex", "Унисекс"),
                ],
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="watches/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="material",
            field=models.CharField(
                choices=[
                    ("plastic", "Пластик"),
                    ("aluminum", "Алюминий"),
                    ("steel", "Нержавеющая сталь"),
                ],
                max_length=100,
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement",
            field=models.CharField(
                choices=[
                    ("mechanical", "Механические"),
                    ("automatic", "Автоматические"),
                    ("quartz", "Кварцевые"),
                ],
                max_length=50,
                verbose_name="Механизм",
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(
                choices=[("yes", "Да"), ("no", "Нет")],
                max_length=50,
                verbose_name="Водостойкость",
            ),
        ),
        migrations.AddField(
            model_name="watch",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watches",
                to="app.author",
                verbose_name="Автор",
            ),
        ),
    ]
