# Generated by Django 4.2.18 on 2025-04-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_author_alter_watch_brand_alter_watch_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="watches/gallery/")),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.watch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение часов",
                "verbose_name_plural": "Изображения часов",
            },
        ),
    ]
