# Generated by Django 4.2.18 on 2025-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_watchimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Загрузите MP4/MOV видео (макс. 100MB)",
                null=True,
                upload_to="watch_videos/",
                verbose_name="Видео часов",
            ),
        ),
    ]
